### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by m-renaud** [m-renaud/libdlibxx#4]
There are currently no test for this code (unit or CI). We should add at the minimum tests that verify that this still compiles under the most commonly used compilers (g++ and clang with c++11, 14, and 17 features).

**Comment by m-renaud** [comment]
Once test suite is created we should set it up to run as CI #5.

**Comment by bigdavedev** [comment]
@m-renaud Please see my [testing](https://github.com/PterabyteGames/libdlibxx/tree/testing) branch in my fork.

Unit testing is enabled by providing `DLIBXX_ENABLE_TESTS=ON` when invoking `cmake`.

I have opted to use googlemock since it is what I am most familiar with. I have written a mock to handle the `dl*` calls allowing me to hook in my own return values.

Let me know what you think.

**Comment by m-renaud** [comment]
Really sorry for the delay, I'll take a look as soon as I have a chance tomorrow!

**Comment by m-renaud** [comment]
Actually, can you create a pull request so I can leave comments there? Thanks!

**Comment by m-renaud** [comment]
Thanks Dave!
